# Generated by Django 5.2 on 2026-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
