# Generated by Django 5.1.1 on 2026-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_payment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
